[package]
name = "vvcore"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "vvcore"

[dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[build-dependencies]
uniffi_build = "0.26.1"
uniffi_bindgen = "0.26.1"
